[package]
name = "sprout"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.5.1", features = ["desktop", "router"] }
dirs = "5.0.1"
json5 = "0.4.1"
rfd = "0.14.1"
serde = { version = "1.0.203", features = ["derive"] }
