[application]
name = "Sprout"
default_platform = "desktop"  # value: web | desktop
hot_reload = true
out_dir = "dist"  # Web `build` & `serve` dist path
asset_dir = "public"  # resource (static) file folder

[web.app]
title = "Sprout | Stardew Valley Mod Manager"  # HTML title tag content

[web.watcher]
index_on_404 = true
watch_path = ["src"]

# include `assets` in web platform
[web.resource]

# CSS style file
# style = ["./public/global.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[application.plugins]

available = true

required = []

[bundle]
# Bundle identifier
identifier = "me.raforaweso"

# Bundle publisher
publisher = "Raforawesome"

# Bundle icon
icon = [
    "public/icon.iconset/*",
    "public/icon.icns",
    "public/icon.ico",
    "public/sprout@1x-square.png",
    "/icon.iconset/*",
    "/icon.icns",
    "/icon.ico",
    "/sprout@1x-square.png",
]

# Bundle resources
resources = ["public/*"]

# Bundle copyright
copyright = ""

# Bundle category
category = "Utility"

# Bundle short description
short_description = "A simple stardew valley mod manager."

# Bundle long description
long_description = """
Simple GUI tool to manage SMAPI mods for Stardew Valley.
"""
